require "kuzicki.launch"
require "kuzicki.options"
require "kuzicki.keymaps"
require "kuzicki.autocmds"
require "kuzicki.neovide"
spec "kuzicki.colorscheme"
spec "kuzicki.devicons"
spec "kuzicki.treesitter"
spec "kuzicki.mason"
spec "kuzicki.schemastore"
spec "kuzicki.lspconfig"
spec "kuzicki.cmp"
spec "kuzicki.none-ls"
spec "kuzicki.whichkey"
spec "kuzicki.telescope"
spec "kuzicki.nvimtree"
spec "kuzicki.comment"
spec "kuzicki.lualine"
-- spec "kuzicki.breadcrumbs"
spec "kuzicki.navic"
spec "kuzicki.harpoon"
spec "kuzicki.toggleterm"
spec "kuzicki.note"
spec "kuzicki.overseer"
spec "kuzicki.dap"
spec "kuzicki.guess-indent"
spec "kuzicki.cmake-tools"
spec "kuzicki.autopairs"
spec "kuzicki.leap" -- checking instead of lightspeed
spec "kuzicki.project"
-- spec "kuzicki.indentline" kinda laggy
spec "kuzicki.alpha"
spec "kuzicki.noice"
spec "kuzicki.various_textobjects"
-- spec "kuzicki.lsp_signature"
-- spec "kuzicki.extras.neoscroll"
-- spec "kuzicki.extras.illuminate" highlight words based on LSP
spec "kuzicki.extras.ufo"
spec "kuzicki.extras.cellular-automaton"

-- jupyter notebook
spec "kuzicki.jupyter.molten"

require "kuzicki.lazy"

--"C:\Users\TheBestComputer\AppData\Local\nvim\init.lua"  r! echo "%:p"
"C:\Users\Kuzicki\AppData\Local\nvim\init.lua" 
