require "kuzicki.launch"
require "kuzicki.options"
require "kuzicki.keymaps"
require "kuzicki.autocmds"
spec "kuzicki.colorscheme"
spec "kuzicki.devicons"
spec "kuzicki.treesitter"
spec "kuzicki.mason"
spec "kuzicki.schemastore"
spec "kuzicki.lspconfig"
spec "kuzicki.cmp"
spec "kuzicki.none-ls"
spec "kuzicki.whichkey"
spec "kuzicki.telescope"
spec "kuzicki.nvimtree"
spec "kuzicki.comment"
spec "kuzicki.lualine"
spec "kuzicki.breadcrumbs"
spec "kuzicki.navic"
spec "kuzicki.harpoon"
spec "kuzicki.toggleterm"
-- spec "kuzicki.overseer"
spec "kuzicki.cmake-tools"
spec "kuzicki.autopairs"
spec "kuzicki.indentline"
-- spec "kuzicki.extras.neoscroll"
-- spec "kuzicki.extras.illuminate" highlight words based on LSP
spec "kuzicki.extras.ufo"
spec "kuzicki.extras.cellular-automaton"
require "kuzicki.lazy"
